name: flutter_lab_assignment_3
description: A Flutter app that fetches albums and photos from JSONPlaceholder API
version: 1.0.0
environment:
  sdk: 3.8.0
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_bloc: ^9.1.1
  go_router: ^15.1.2
  dio: ^5.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
flutter:
  uses-material-design: true